accounts/urls.py
from django.urls import path
from .views import SignupPageView

urlpatterns = [
    path('signup/', SignupPageView.as_view(), name='signup')
]

django_studio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',  include('accounts.urls')),
    path('', include('generator.urls')),
]

generator/urls.py
from django.urls import path
from .views import *

app_name = 'generator'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('project/', Project.as_view(), name='project')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

generator/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        models = get_user_model()
        fields = ('email', 'username',)

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm

class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

generator/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class Home(TemplateView):
    template_name = "home.html"

class Project(TemplateView):
    template_name = "project.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>NAVBARRR!</h1>
    {% block content%}
    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Django-Studio | Home{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        Hello {{user.email}}
        <h2>Create a new project</h2>
        <a href="{% url 'logout' %}">Log Out</a>
        <a href="{% url 'generator:project' %}" target="_blank" class="main-btn" rel="noopener noreferrer">Create New Project</a>
    {% else %}
        <p>Please login or create an account</p>
        <a href="{% url 'login' %}">Log in</a>
        <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
{% endblock %}
</body>
</html>

templates/project.html
{% extends 'base.html' %}
{% block title %}Django-Studio | Project{% endblock %}
{% block content %}
    <h2>Project Name</h2>
    <input type="text">
{% endblock %}
</body>
</html>